apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomato
  labels:
    app: zomato

spec:
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1

  selector:
    matchLabels:
      app: zomato

  template:
    metadata:
      labels:
        app: zomato

    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: zomato
                topologyKey: kubernetes.io/hostname

      containers:
        - name: zomato
          image: 476603352136.dkr.ecr.ap-south-1.amazonaws.com/kb-zomato:build-41
          imagePullPolicy: Always

          ports:
            - containerPort: 3000

          env:
            - name: HOST
              value: "0.0.0.0"
